baseurl = "http://farazkhanfk7.github.io"
title = "Hasan Faraz Khan"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 10

[services]
[services.disqus]
disqusShortname = "farazkhanfk7"

[markup.highlight]
style = "github-dark"

[params]
  author = "Hasan Faraz Khan"
  info = "Software Engineer ( Backend )"
  description = "intriguing possibilities"
  keywords = "blog,developer,personal"
  avatarurl = "https://avatars.githubusercontent.com/u/47111858?v=4"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/farazkhanfk7"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/farazkhanfk7/"
[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/batcypher/"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "Blogs"
  weight = 2
  url  = "posts/"
[[menu.main]]
  name = "Resume"
  weight = 3
  url  = "resume/"

